# Generated by Django 5.2.4 on 2025-07-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField()),
            ],
            options={
                'verbose_name': 'userAuth',
                'verbose_name_plural': 'userAuths',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
