# Generated by Django 5.2.4 on 2025-07-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauth',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='pwd',
        ),
        migrations.AddField(
            model_name='userauth',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userauth',
            name='username',
            field=models.CharField(default=2, max_length=45, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userauth',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='userauth',
            table=None,
        ),
    ]
